global:
  name: FINOS Landscape
  short_name: FINOS
  repo: finos/finos-landscape
  website: https://landscape.finos.org
  short_domain: l.finos.org
  company_url: https://finos.org
  email: info@finos.org
  self: https://www.crunchbase.com/organization/finos-foundation
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: FINOS Landscape
    fb_admin: grizzwolf
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@finosfoundation'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: FINOS Members
  hide_best_practices: true
  flags:
    hide_license_for_categories:
      - FINOS Members
twitter:
  search: landscape.finos.org
  url: https://landscape.finos.org
  text: FINOS Landscape
relation:
  label: FINOS Relation
  url: FINOS
  values:
    - id: hosted
      label: FINOS Foundation Projects
      children:
        - id: active
          label: FINOS Active Projects
          prefix: FINOS
          tag: Active Project
          color: '#48A934'
          big_picture_label: FINOS Active
          big_picture_color: rgb(72,169,52)
          big_picture_order: 1
        - id: incubating
          label: FINOS Incubating Projects
          prefix: FINOS
          tag: Incubating Project
          color: '#D2C53A'
          big_picture_label: FINOS Incubating
          big_picture_color: rgb(210,197,58)
          big_picture_order: 2
        - id: archived
          label: FINOS Archived Projects
          prefix: FINOS
          tag: Archived Project
          color: '#A2ABAA'
          big_picture_label: FINOS Archived
          big_picture_color: rgb(162,171,170)
          big_picture_order: 3
        - id: sig
          label: Special Interest Group
          prefix: FINOS
          tag: Special Interest Group
          color: rgb(0,181,226)
          big_picture_label: Special Interest Group
          big_picture_color: rgb(0,181,226)
          big_picture_order: 4
    - id: company
      label: FINOS Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: Organizations
      tag: FINOS Members
    - id: false
      label: Non-FINOS Foundation Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: FINOS
    label: Platinum Member
    funding: Platinum
    is_large: true
  Gold:
    name: FINOS
    label: Gold Member
    funding: Gold
    is_large: true
  Silver:
    name: FINOS
    label: Silver Member
    funding: Silver
  Associate:
    name: FINOS
    label: Associate Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>FINOS Landscape</h1> The FINOS Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/open-source-finance-forum/
    image: /images/2022-OSFF.jpeg
    title: Open Source in Finance Forum 2022
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    fullscreen_hide_grey_logos: true
    tab_index: -1
    url: landscape
    name: Landscape
    title: FINOS Landscape
    fullscreen_header: See the interactive landscape at l.finos.org
    size:
      width: 1020
      height: 840
    fullscreen_size:
      width: 1020
      height: 840
    elements:
      - type: HorizontalCategory
        category: Applications
        rows: 4
        width: 570
        height: 180
        top: 0
        left: 0
        color: rgb(0,181,226)
        fit_width: true
      - type: HorizontalCategory
        category: Platforms & Runtimes
        rows: 4
        width: 500
        height: 180
        top: 0
        left: 590
        color: rgb(215,200,38)
        fit_width: true
      - type: HorizontalCategory
        category: Data & Business Logic
        rows: 4
        width: 730
        height: 180
        top: 200
        left: 0
        color: rgb(0,134,191)
        fit_width: true
      - type: HorizontalCategory
        category: Legend
        rows: 4
        width: 200
        height: 180
        top: 200
        left: 750
        color: rgb(0,181,226)
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 4
        width: 160
        height: 180
        top: 410
        left: 0
        color: rgb(67,176,42)
        fit_width: true
      - type: HorizontalCategory
        category: Enablement
        rows: 4
        width: 650
        height: 180
        top: 410
        left: 180
        color: rgb(107,202,186)
        fit_width: true
      - type: LandscapeInfo
        width: 430
        height: 200
        top: 620
        left: 0
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Financial Services Open Source and Open Standard Projects hosted by the FINOS Foundation. 
              Community contributions are more than welcome, please raise an issue or pull request at github.com/finos/finos-landscape.
            top: 65
            left: 130
            right: 20
            font_size: 11
          - type: image
            image: qr.svg
            top: 33
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.finos.org
            top: 130
            left: 24
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 120
            right: 195
            top: 20
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 100
            right: 20
            top: 20
            title: FINOS Foundation Logo
  third:
    tab_index: 1
    url: members
    name: Members
    title: FINOS Members
    fullscreen_header: Become a FINOS member at www.finos.org/membership-benefits
    fullscreen_hide_grey_logos: true
    elements:
      - type: VerticalCategory
        category: Platinum
        width: 1020
        height: 190
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
      - type: VerticalCategory
        category: Gold
        width: 1020
        height: 190
        top: 200
        left: 0
        color: '#d4af37'
        fit_width: true
      - type: VerticalCategory
        category: Silver
        cols: 30
        width: 1020
        height: 140
        top: 400
        left: 0
        color: '#C0C0C0'
        fit_width: true
      - type: VerticalCategory
        category: Associate
        cols: 30
        width: 1020
        height: 140
        top: 550
        left: 0
        color: rgb(0,0,0)
        fit_height: true
    category: FINOS Members
prerender:
  members: /card-mode?style=borderless&category=finos-members&grouping=category&embed=yes
test:
  header: FINOS Landscape
  section: FINOS Active Projects
  logo: cla-bot.svg
