global:
  name: FINOS Landscape
  short_name: FINOS
  repo: finos/FINOS-landscape
  website: 'https://landscape.finos.org'
  short_domain: l.finos.org
  company_url: 'https://finos.org'
  email: info@FINOS.org
  self: 'https://www.crunchbase.com/organization/symphony-software-foundation'
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: FINOS Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@FINOSFdn'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: FINOS Foundation Member
  flags:
    hide_license_for_categories:
      - FINOS Adopter
      - FINOS Foundation Member
twitter:
  search: landscape.FINOS.org
  url: 'https://landscape.finos.org'
  text: FINOS Landscape
relation:
  label: FINOS Relation
  url: FINOS
  values:
    - id: hosted
      label: FINOS Foundation Projects
      children:
        - id: foundationproject
          label: FINOS Foundation Projects
          prefix: FINOS
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: FINOS Foundation Project
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: FINOS Foundation Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: FINOS Foundation Member Products/Projects
      tag: FINOS Foundation Member
    - id: false
      label: Non-FINOS Foundation Member Products/Projects
      url: 'no'
membership:
  General:
    name: FINOS
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>FINOS Landscape</h1> The FINOS Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=graphql_landscape&utm_medium=web&utm_campaign=kccnceu20'
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: FINOS Landscape
    fullscreen_header: See the interactive landscape at l.FINOS.org
    size:
      width: 1020
      height: 840
    fullscreen_size:
      width: 1020
      height: 840
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 325
        height: 160
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Services
        rows: 3
        width: 280
        height: 160
        top: 0
        left: 345
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Databases
        rows: 3
        width: 325
        height: 160
        top: 0
        left: 645
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: FINOS Adopter
        rows: 6
        width: 970
        height: 320
        top: 180
        left: 0
        color: 'rgb(126,115,14)'
        fit_width: true
      - type: HorizontalCategory
        category: FINOS Foundation Member
        rows: 4
        width: 650
        height: 200
        top: 540
        left: 0
        color: 'rgb(103,66,18)'
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 200
        top: 540
        left: 670
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the FINOS community, and also shows the member organizations of the FINOS Foundation.
            top: 55
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.FINOS.org
            top: 140
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 190
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 10
            top: 10
            title: FINOS Foundation Logo
test:
  header: FINOS Landscape
  section: FINOS Foundation Member
  logo: ibm.svg
